viber-cp/music/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
app_name = 'music'

urlpatterns = [

    # ---------------------------------------LOGIN AND SIGNUP----------------------------------------------------------

    url(r'^register/$', views.SignUpView.as_view(), name='register'),

    url(r'^register/edit/$', views.user_profile, name='edit'),


    url(r'^login/$', auth_views.login, name='login'),

    url(r'^logout/$', auth_views.logout, {'template_name': 'registration/logged_out.html'}, name='logout'),


    # ---------------------------------------PASSWORD CHANGE-----------------------------------------------------------

    url(r'^password-change/$', auth_views.password_change,
        {'template_name': 'registration/password_change_form.html',
         'post_change_redirect': 'registration/password_change_done.html'}, name='password_change'),

    url(r'^password-change/registration/password_change_done.html/$', auth_views.password_change_done,
        {'template_name':'registration/password_change_done.html'}, name='password_change_done'),



    # ----------------------------------------PASSWORD RESET------------------------------------------------------------

    url(r'password-reset/$' ,
        PasswordResetView.as_view(template_name='music/password_reset_form.html',
         success_url=reverse_lazy('music:password_reset_done'),  email_template_name='music/password_reset_email.html',
         subject_template_name='music/password_reset_subject.txt'), name='password_reset'),

    url(r'password-reset/done/$' , PasswordResetDoneView.as_view(template_name='music/password_reset_done.html') ,name='password_reset_done'),


    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(template_name='music/password_reset_confirm.html', success_url=reverse_lazy('music:password_reset_complete')), name="password_reset_confirm" ),


    url(r'^reset/complete/$', PasswordResetCompleteView.as_view(template_name='music/password_reset_complete.html'), name="password_reset_complete"),



    # ---------------------------------------ALBUM AREA----------------------------------------------------------------
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/3/

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # ?P<> used to store int id in url pattern and [0-9]+ conains all the possible integers

    # /music/album/add/
    url(r'^album/add/$', views.CreateAlbum.as_view(), name='album-add'),

    # /music/album/3
    url(r'^album/(?P<pk>[0-9]+)/$', views.UpdateAlbum.as_view(), name='album-update'),

    # /music/3/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.DeleteAlbum.as_view(), name='album-delete'),




    # --------------------------------------------SONG AREA--------------------------------------------------------

    # /music/songs
    url(r'^songs/$', views.Index1View1.as_view(), name='song-list'),

    # /music/songs/3
    url(r'^songs/(?P<pk>[0-9]+)/$', views.Index1View1.as_view(), name='song-added-view'),

    # /music/songs/add
    url(r'^songs/add/$', views.CreateSong.as_view(), name='song-add'),

    # /music/songs/3/update
    url(r'^songs/(?P<pk>[0-9]+)/update/$', views.UpdateSong.as_view(), name='song-update'),

    # /music/songs/3/delete
    url(r'^songs/(?P<pk>[0-9]+)/delete/$', views.DeleteSong.as_view(), name='song-delete'),



]

viber-cp/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [


    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viber-cp/music/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Album(models.Model):
    artist = models.CharField(max_length=50)
    album_title = models.CharField(max_length=120)
    genre = models.CharField(max_length=10)
    album_logo = models.FileField()
    is_fovorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})  #for creating new

    def __str__(self):
        return self.album_title + '-' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, default="no_album")
    file_type = models.CharField(max_length=15)
    song_title = models.CharField(max_length=250)
    song_file = models.FileField(default="no_song")

    def get_absolute_url(self):
        return reverse('music:song-added-view', kwargs={'pk': self.pk})

    def __str__(self):
        return self.song_title


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10,blank=True)
    address = models.CharField(max_length=30,blank=False)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

viber-cp/music/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from music.models import Profile
from django.utils.translation import gettext as _



class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=30)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']




class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = [ 'phone', 'address']
        labels ={'phone':'mob', 'user':'client'}


viber-cp/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album, Song
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import SignUpForm,ProfileForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _

# ----------------------------------------ALBUM AREA CRUD-----------------------------------------------------------


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'  # all_objects can be used which is by default contain all the objects of a class

    def get_queryset(self):
        return Album.objects.raw('SELECT * FROM music_album ORDER BY album_title ASC')


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class CreateAlbum(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo', 'is_fovorite']  # template name need not be defined explicitly because
    # create view automatically get default html file as
    # model name_form.html    e:g (album_form.html)


class UpdateAlbum(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo', 'is_fovorite']


class DeleteAlbum(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


# -----------------------------------------SONG CRUD AREA--------------------------------------------------------------


class Index1View1(LoginRequiredMixin, generic.ListView):
    template_name = 'music/index1.html'
    context_object_name = 'all_songs'

    def get_queryset(self):
        return Song.objects.raw('SELECT * FROM music_song ORDER BY song_title ASC')


class CreateSong(LoginRequiredMixin, CreateView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'song_file']


class UpdateSong(LoginRequiredMixin, UpdateView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'song_file']


class DeleteSong(LoginRequiredMixin, DeleteView):
    model = Song
    success_url = reverse_lazy('music:song-list')

# -----------------------------------------LOG IN AND AUTHENTICATION------------------------------------------------


class SignUpView(View):
    form_class = SignUpForm
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            return redirect('music:edit')
        return render(request, self.template_name, {'form': form})


@login_required
def user_profile(request):
    if request.method == 'POST':

        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, _('your Profile Updated'))
            return redirect('music:index')
        else:
            messages.success(request, _('Please Enter Correct Information'))

    else:

        profile_form = ProfileForm(request.POST, instance=request.user.profile) #important
    return render(request,'music/profile.html', {'profile_form': profile_form})


















# from django.http import HttpResponse
# from django.http import Http404
# from django.template import loader
# OR
# from django.shortcuts import render,get_object_or_404
# from .models import Album, Song

# def index(request):
# context = { 'all_albums': all_albums,}
# return render(request, 'music/index.html', context)


# def detail(request ,album_id):
# album = get_object_or_404(Album, id = album_id)
# return render(request, 'music/detail.html', {'album': album})


# def favorite(request,album_id):
# album = get_object_or_404(Album, id=album_id)

# try:
# selected_song = album.song_set.get(pk = request.POST['song'])  #obtain particular song from Song class which is inherited from Album class
# except(KeyError, Song.DoesNotExist):
# return  render(request, 'music/detail.html', {
# 'album': album,
# 'error_message': "you did not select any song"
# } )
# else:
# selected_song.is_favorite = True
#  selected_song.save()
# return render(request, 'music/detail.html', {'album': album})

viber-cp/music/templates/music/album_form.html
{% extends 'music/base.html'  %}
{% block title%}
     Add new Album
{% endblock %}


{% block body%}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SUBMIT</button>
                            </div>
                        </div>
                    </form>
                 </div>
              </div>
         </div>
     </div>
</div>
{% endblock%}

viber-cp/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
      <link rel="icon" href="music/images/login.ico" type="image/x-icon" />
    <title>
      {% block title%}
      {% endblock %}
    </title>

    <!-- Bootstrap -->
    {% load staticfiles %}
    <link href="{% static 'music/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    {% load staticfiles %}
    <link href="{% static 'music/style.css' %}" rel="stylesheet" />

  </head>

 <body>

     {% load staticfiles %}
    <script src="{% static 'music/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
     {% load staticfiles %}
    <script src="{% static 'music/bootstrap/js/bootstrap.min.js' %}"></script>

     <!-- ------------------------------- WORKING AREA BELOW------------------------------------------- -->

     <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{%url 'music:index' %}">VIBER</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            {% if request.user.is_authenticated %}
                <li><a class="nav-names" href="{%url 'music:index' %}"><span class="glyphicon glyphicon-cd"></span>&nbsp;Album</a></li>&nbsp;
                <li><a class="nav-names" href="{% url 'music:album-add'%}"><span class="glyphicon glyphicon-plus"></span> Add Album</a></li>
                <li><a class="nav-names" href="{%url 'music:song-list'%}"><span class="glyphicon glyphicon-music"></span>&nbsp;Songs</a></li>&nbsp;
                <li><a class="nav-names" href="{% url 'music:song-add'%}"><span class="glyphicon glyphicon-plus"></span> Add Song</a></li>
                <form class="navbar-form navbar-left" action="/action_page.php">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                <button type="submit" class="btn btn-default">Search</button>
                </form>

        </ul>
             {% endif%}



                        <ul class="nav navbar-nav navbar-right">
                            {% if request.user.is_authenticated %}
                                <li> <a href="#"><span class="glyphicon glyphicon-user"></span> Hello&nbsp;{{request.user.username}}</a></li>
                                <li><a href="{% url 'music:logout'%}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>

                            {% else %}
                                  <li><a href="{% url 'music:login'%}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>

                            {%endif%}

      </ul>
    </div>
  </div>
</nav>
{%block body%}

 {%endblock%}


</body>
</html>

viber-cp/music/templates/music/detail.html

<!--
    Here album and song are classes used to call
    corrosponding columns bcoz class with lower case
    is specific instance where as class with upper case
    is a type.
        -->

<!-- album class used to fetch data from song class as song_set.all(remain same)-->
{% extends 'music/base.html'  %}

{% block title%}
     Album Detail
{% endblock %}

{% block body %}



<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="albums-details">
                <img id="logo" src="{{album.album_logo.url}}" width="150px" height="150px">
                <h1>{{album.album_title}}</h1>
                <h3>Artist: {{album.artist}}</h3>
            </div>
        </div>

{%if error_message%}
    <p><strong>{{Error_message}}</strong></p>
{% endif %}

 <div class="col-sm-6">
     <table class="table table-striped">
         <thead>
            <tr>
                <th> S. No.</th>
                <th> Title</th>
                <th> Play/Download</th>
            </tr>
         </thead>
                {% for song in album.song_set.all %} <!--because songs are foreign key of albums-->
                    <tbody>
                            <tr>
                                <td>{{forloop.counter}} </td>
                                <td> {{song.song_title}}</td>
                                <td><audio controls="audiocontrols">
                                        <source src="{{song.song_file.url}}">
                                    </audio>
                                </td>
                            </tr>
                        </tbody>
                {%endfor%}
            </table>
        </div>
    </div>
</div>




{% endblock %}


viber-cp/music/templates/music/edit_form.html
{% extends 'music/base.html'  %}
{% block title%}
     Register
{% endblock %}


{% block body%}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create New Account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SUBMIT</button>
                            </div>
                        </div>
                    </form>
                 </div>
              </div>
         </div>
     </div>
</div>

{% endblock%}

viber-cp/music/templates/music/form_template.html



 {% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">
                {{field.errors}}
            </span>
        </div>

        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>




    </div>

 {% endfor %}

viber-cp/music/templates/music/index.html
{% extends 'music/base.html'  %}


{% block title%}
     Albums
{% endblock %}


{% block body %}
{% if all_albums %}
        <div class="container-fluid">
             <div class="row">

    {% for album in all_albums %}

             <div class="col-sm-4">
                 <div class="albums">
                        <a href ="{{album.id}}">
                            <img class="logo-image" src="{{ album.album_logo.url }}" width="300px" height="300px"/></a><br>
                                <u><h1>{{album.album_title}}</h1></u>
                                    <h3>{{album.artist}}</h3>
                        <div class="buttons">
                    <a href="{{ album.id }}"><button type="button" class="btn btn-primary btn-md">View Details</button></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                       {%if album.is_fovorite%}
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-heart"></span></button>


                       {%endif%}

                        <form action=" album/{{album.id }}/" method="post" style="display: inline;">
                                {%csrf_token %}
                                <input type="hidden" name=album_id" value="{{album.id}}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-cog"></span>
                                </button>
                            </form>
                            <form action="album/{{album.id}}/delete/" method="post" style="display: inline;">
                                {%csrf_token %}
                                <input type="hidden" name="album_id" value="{{album.id}}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                         </div>

                 </div>
         </div>


    {% endfor %}
             </div>
 </div>
{% else %}
    <h2>NO albums </h2>
{% endif %}

<style>

.albums
{
background-color: white;
width:auto;
height:auto;
margin-top:10px;
padding:20px;
text-align:center;
font-family:cursive;
color: black;
font-size: 20px;
font-weight:900;
border:6px doted black;

}
</style>
{% endblock %}



viber-cp/music/templates/music/index1.html
{% extends 'music/base.html'  %}
{% block body %}



<div class="container">
    <div class="row">
     {%if error_message%}
        <p><strong>{{Error_message}}</strong></p>
    {% endif %}
            <table class="table table-striped">
         <thead>
            <tr>
                <th> S. No.</th>
                <th> Title</th>
                <th> Play/Download</th>
            </tr>
         </thead>
                {% for song in all_songs %}
                    <tbody>
                            <tr>
                                <td>{{forloop.counter}} </td>
                                <td> {{song.song_title}}</td>
                                <td><audio controls="audiocontrols">
                                        <source src="{{song.song_file.url}}">
                                    </audio>
                                </td>
                                <td>
                                    <form action="{% url 'music:song-delete' song.id %}" method="post" style="display: inline;">
                                {%csrf_token %}
                                <input type="hidden" name="song_id" value="{{song.id}}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                                </td>

                            </tr>
                        </tbody>
                {%endfor%}
            </table>
    </div>
</div>

{% endblock%}

viber-cp/music/templates/music/password_reset_confirm.html
{% extends 'music/base.html'  %}
{% block title%}
     Log in
{% endblock %}

{%block body%}

{%if validlink %}
    <form action="." method="post">
        {{form.as_p}}
        {% csrf_token%}
        <p><input type="submit" value="Change my password"></p>
    </form>

{%else%}

    <p>password link is invalid</p>
{%endif%}
{%endblock%}

viber-cp/music/templates/music/password_reset_done.html
{% extends 'music/base.html'  %}
{% block title%}
     Log in
{% endblock %}

{%block body%}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                     <h1>SomeOne Asked for the Password Reset </h1>
                     <h2>We Emailed you the link Containing Reset page </h2>
                     <h3>If you not received any email it must be system error or you entered a un-valid Email Address</h3>
                            </div>
                        </div>
                 </div>
              </div>
         </div>
     </div>
</div>

{%endblock%}

viber-cp/music/templates/music/password_reset_email.html
someone asked {{email}}.follow the link:
{{protocol}}://{{domain}}{% url 'music:password_reset_confirm' uidb64=uid token=token %}

your user name:{{user.get_username}}

viber-cp/music/templates/music/profile.html
{% extends 'music/base.html'  %}
{% block body%}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                         {{profile_form.as_p}}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SUBMIT</button>
                            </div>
                        </div>
                    </form>


                 </div>
              </div>
         </div>
     </div>
</div>
{% endblock%}

viber-cp/music/templates/music/register_done.html
{% extends 'music/base.html'  %}
{% block title%}
     Log in
{% endblock %}


{%block body%}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                     <h1>Your Account Created Successfully </h1>
                            </div>
                        </div>
                 </div>
              </div>
         </div>
     </div>
</div>

{%endblock%}

viber-cp/music/templates/music/registration_form.html
{% extends 'music/base.html'  %}
{% block title%}
     Register
{% endblock %}


{% block body%}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create New Account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SUBMIT</button>
                            </div>
                        </div>
                    </form>
                 </div>
              </div>
         </div>
     </div>
</div>

{% endblock%}

viber-cp/music/templates/music/song_form.html
{% extends 'music/base.html'  %}
{% block body%}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SUBMIT</button>
                            </div>
                        </div>
                    </form>
                 </div>
              </div>
         </div>
     </div>
</div>






{% endblock%}